# Generated by Django 5.1.2 on 2024-11-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_login_email_alter_login_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='age',
        ),
        migrations.RemoveField(
            model_name='login',
            name='image',
        ),
    ]
