# Generated by Django 5.1.2 on 2024-11-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_login_age_remove_login_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
