# Generated by Django 5.1.2 on 2024-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_login_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
    ]
