# Generated by Django 5.1.3 on 2024-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_login_age_alter_login_email_alter_login_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
