# Generated by Django 5.1.3 on 2024-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_login_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=40)),
                ('rating', models.DecimalField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Romantic', 'Romantic'), ('Science-Fiction', 'Science-Fiction')], decimal_places=1, max_digits=2, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
