# Generated by Django 5.1.3 on 2024-11-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name': 'User'},
        ),
        migrations.AddField(
            model_name='movies',
            name='user',
            field=models.ManyToManyField(to='pages.login'),
        ),
        migrations.AlterField(
            model_name='login',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
