# Generated by Django 5.1.3 on 2024-11-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_login_options_movies_user_alter_login_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
