# Generated by Django 5.1.3 on 2024-11-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_movies_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.AddField(
            model_name='login',
            name='movie',
            field=models.ManyToManyField(to='pages.movie'),
        ),
    ]
