# Generated by Django 5.1.3 on 2024-11-29 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_movie_rating_alter_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_trailer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
