# Generated by Django 5.1.3 on 2024-12-18 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_movie_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('image', models.ImageField(null=True, upload_to='photos/%y/%m/%d')),
                ('movie_link', models.TextField(null=True)),
                ('movie_trailer', models.CharField(max_length=1000)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('image', models.ImageField(null=True, upload_to='photos/%y/%m/%d')),
                ('movie_link', models.TextField(null=True)),
                ('movie_trailer', models.CharField(max_length=1000, null=True)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('image', models.ImageField(null=True, upload_to='photos/%y/%m/%d')),
                ('movie_link', models.TextField(null=True)),
                ('movie_trailer', models.CharField(max_length=1000)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
