# Generated by Django 5.1.3 on 2024-12-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_delete_animation_delete_series_alter_film_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='age',
        ),
    ]
