# Generated by Django 5.1.3 on 2024-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_login_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
